---
  - name: Check whether /etc/yum.conf contains "exclude"
    command: grep "exclude=" /etc/yum.conf | awk -F '=' '{print$2}'
    register: exclude_packages
    check_mode: no
    ignore_errors: yes
    changed_when: no
  
  debug: msg={{ exclude_packages }}

  - name: "Template to override /etc/yum.conf"
    template:
      src: "yum.conf.j2"
      dest: "/etc/yum.conf"
      owner: root
      group: root
      mode: '0644'
