---
  - name: "Check whether /etc/yum.conf contains exclude"
    lineinfile:
      path: /etc/yum.conf
      line: "^exclude="
      state: present
      backup: yes
    register: exclude_pkgs

  - debug: msg={{ exclude_pkgs }}

  - name: "Template to override /etc/yum.conf"
    template:
      src: "yum.conf.j2"
      dest: "/etc/yum.conf"
      owner: root
      group: root
      mode: '0644'
